detectors:
  - name: "nordvpn_official_vs_reseller"
    enabled: true
    params:
      source_a:
        url: "https://nordvpn.com/pricing/"
        price_regex: 'data-testid="price">\\$([0-9]+\\.?[0-9]*)'

      source_b:
        url: "https://stacksocial.com/sales/nordvpn-2-year-subscription"
        price_regex: '\\$([0-9]+\\.?[0-9]*)'

      min_abs_profit: 20
      min_roi: 0.20
